@echo off
@echo Creating the directory structure and files for you. Please Wait.
@echo  Creating assets folder...
mkdir assets
@echo  Going into assets folder...
cd assets
@echo Creating javascript folder...
mkdir javascript 
@echo Creating css folder...
mkdir css
@echo Creating images folder...
mkdir images
cd ..
@echo Creating index.html file...
@echo Creating app.js file...
@echo Creating style.css file...
@echo Creating resets.css file...
touch index.html assets/javascript/app.js assets/css/style.css assets/css/resets.css
@echo Done... (Remember Say "Thank You Ryan")

